CREATE TABLE SCHEMA_MIGRATIONS (
  VERSION    INTEGER   NOT NULL,
  APPLIED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT PK_SCHEMA_MIGRATIONS PRIMARY KEY (VERSION)
)^

CREATE GENERATOR GEN_EXEMPLO_ID^

CREATE TABLE EXEMPLO (
  ID   INTEGER      NOT NULL,
  NOME VARCHAR(100) NOT NULL,
  CONSTRAINT PK_EXEMPLO PRIMARY KEY (ID)
)^

CREATE TRIGGER BI_EXEMPLO FOR EXEMPLO
  ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR GEN_EXEMPLO_ID;
END^
